### PR TITLE
Rename triangle icons

### PR DESCRIPTION
**Pull request by ashygee**
This PR renames the 16px `triangle-` icons to `caret-` to follow the same naming convention as the 24px icons to be more descriptive.﻿

### CODE REVIEW

**Comment by colebemis** [comment]
I like this naming better too 👍Do we want to make this name change now? Or should we include it as part of the v2 updates?

**Comment by ashygee** [comment]
> I like this naming better too 👍Do we want to make this name change now? Or should we include it as part of the v2 updates?

@colebemis I think we can just make the name change now since I already did it in Figma 😂. But it's up to you.

**Comment by colebemis** [comment]
Renaming an icon would be a breaking change to the library. So I think it would be better to batch this breaking change with all the other breaking changes in v2 so we only have to bump the major version number once (`9.6.0` → `10.0.0` instead of `9.6.0` → `10.0.0` → `11.0.0`).

**Comment by colebemis** [comment]
Oh, I didn't realize this PR was in the `octicons-v2` repo (not `primer/octicons`). Let's go ahead and merge this! :)

**Comment by colebemis** [comment]
We'll have to rename the triangle icons in the [`v2` branch](https://github.com/primer/octicons/pull/370) in the primer/octicons repo as well.

Also, we'll probably want to archive this repo and start working in the primer/octicons repo soon because it's getting a little confusing 😅

**Pull request merged**
